prometheusNamespace: monitoring
services:
  - name: nginx
    enabled: true
    namespace: ingress-nginx
    k8sname: ingress-nginx
    team: infra
    port: 10254
  - name: flux
    enabled: true
    namespace: flux
    app: flux
    team: infra
    release: flux
