{{- range .Values.services }}
{{- if .enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{.name}}-metrics-servicemonitor
  namespace: {{.promNamespace}}
  labels:
    {{- if .app }}
    app: {{.app}}
    {{- else if .k8sname }}
    app.kubernetes.io/name: {{.k8sname}}
    {{- end }}
    team: {{.team}}
    release: {{.promReleaseLabel}}
spec:
  selector:
    matchLabels:
      {{- if .app }}
      app: {{.app}}
      {{- else if .k8sname }}
      app.kubernetes.io/name: {{.k8sname}}
      {{- end }}
      {{- if .release }}
      release: {{.release}}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{.namespace}}
    any: true
  {{- if .port }}
  endpoints:
  - port: {{.port}}
    interval: 15s
    {{- if .path }}
    path: {{.path}}
    {{- else }}
    path: /metrics
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}