{{- range .Values.services }}
{{- if .enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{.name}}-metrics-servicemonitor
  namespace: {{.promNamespace}}
  labels:
    {{- if .app }}
    app: {{.app}}
    {{- else if .k8sname }}
    app.kubernetes.io/name: {{.k8sname}}
    {{- end }}
    team: {{.team}}
spec:
  selector:
    matchLabels:
      {{- if .app }}
      app: {{.app}}
      {{- else if .k8sname }}
      app.kubernetes.io/name: {{.k8sname}}
      {{- end }}
  endpoints:
  - port: metrics
    interval: 15s
{{- end }}
{{- end }}