{{- range .Values.services }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{.name}}-metrics-servicemonitor
  namespace: {{.Values.prometheusNamespace}}
  labels:
    {{- if .app }}
    app: {{.app}}
    {{ else if .k8sapp }}
    app.kubernetes.io/name: {{.k8sapp}}
    {{- end }}
    team: {{.team}}
spec:
  selector:
    matchLabels:
      {{- if .app }}
      app: {{.app}}
      {{ else if .k8sapp }}
      app.kubernetes.io/name: {{.k8sapp}}
      {{- end }}
  endpoints:
  - port: metrics
    interval: 15s
{{- end }}