acr:
  name: oneesdevacr
dns:
  domain: "1es.io"
  sslCert: sslcert-aks-run
  resourceGroup: compes-bedrock-lab
  image:
    name: "1es/external-dns"
    tag: 720306
aks:
  clusterName: compes-bedrock-lab
  location: westus2
imagePullSecrets: acr-auth