name: "prometheus-operator"
generator: static # Deprecated in fabrikate v1.0.0
type: static # Replaces `generator` in fabrikate v1.0.0
path: "./manifests"
hooks:
  before-install:
    - echo 'installing prometheus-operator'
  after-install:
    - echo 'installed prometheus-operator'
subcomponents:
  - name: "prometheus-operator"
    generator: helm # Deprecated in fabrikate v1.0.0
    type: helm # Replaces `generator` in fabrikate v1.0.0
    source: "https://github.com/helm/charts"
    method: "git"
    path: "stable/prometheus-operator"
    version: "f4743a18769c5405413e1d6cd897bd9c877ce1b1"
