---
apiVersion: v1
kind: Service
metadata:
  name: geneva-services
  labels:
    app: geneva-services
spec:
  type: ClusterIP
  ports:
    - name: mdsd-fluentd-tcp
      protocol: TCP
      port: 24224
      targetPort: 24224
  selector:
    name: geneva-services

---
apiVersion: v1
kind: Service
metadata:
  name: geneva-metrics
  labels:
    app: geneva-services
spec:
  type: ClusterIP
  ports:
    - name: mdm-statsd-udp
      protocol: UDP
      port: 8125
      targetPort: 8125
  selector:
    name: geneva-services-statsd