config:
subcomponents:
  prometheus-operator:
    namespace: monitoring
    injectNamespace: true
    config:
      coreDns:
        enabled: true
      kubeDns:
        enabled: false
      alertmanager:
        alertmanagerSpec:
          logLevel: "debug"
          storage:
            volumeClaimTemplate:
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 10Gi
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            kubernetes.io/tls-acme: "true"
          hosts:
            - "alertmanager-space-westus2.{{.Values.dns.name}}"
          tls:
            - secretName: "{{.Values.dns.sslCert}}"
              hosts:
                - "alertmanager-space-westus2.{{.Values.dns.name}}"
      prometheus:
        prometheusSpec:
          storageSpec:
            volumeClaimTemplate:
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 10Gi
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            kubernetes.io/tls-acme: "true"
          hosts:
            - "prometheus-space-westus2.{{.Values.dns.name}}"
          tls:
            - secretName: "{{.Values.dns.sslCert}}"
              hosts:
                - "prometheus-space-westus2.{{.Values.dns.name}}"
      grafana:
        adminUser: "admin"
        adminPassword: "grafana"
        persistence:
          enabled: true
          accessModes: ["ReadWriteOnce"]
          size: 10Gi
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            kubernetes.io/tls-acme: "true"
          hosts:
            - "grafana-space-westus2.{{.Values.dns.name}}"
          tls:
            - secretName: "{{.Values.dns.sslCert}}"
              hosts:
                - "grafana-space-westus2.{{.Values.dns.name}}"

      kubelet:
        serviceMonitor:
          https: false