config:
subcomponents:
  prometheus-operator:
    namespace: monitoring
    injectNamespace: true
    config:
      # Depending on which DNS solution you have installed in your cluster enable the right exporter
      coreDns:
        enabled: true
      kubeDns:
        enabled: false

      alertmanager:
        alertmanagerSpec:
          logLevel: "debug"
          storage:
            volumeClaimTemplate:
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 10Gi
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            kubernetes.io/tls-acme: "true"
          hosts:
            - "alertmanager-space-westus2.aks.run" # overwriten at HLD
          tls:
            - secretName: "sslcert-aks-run" # overwriten at HLD
              hosts:
                - "alertmanager-space-westus2.aks.run" # overwriten at HLD

      prometheus:
        prometheusSpec:
          storageSpec:
            volumeClaimTemplate:
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 10Gi
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            kubernetes.io/tls-acme: "true"
          hosts:
            - "prometheus-space-westus2.aks.run"
          tls:
            - secretName: "sslcert-aks-run"
              hosts:
                - "prometheus-space-westus2.aks.run"

      grafana:
        adminUser: "admin"
        adminPassword: "grafana"
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            kubernetes.io/tls-acme: "true"
          hosts:
            - "grafana-space-westus2.aks.run"
          tls:
            - secretName: "sslcert-aks-run"
              hosts:
                - "grafana-space-westus2.aks.run"
        persistence:
          enabled: true
          accessModes: ["ReadWriteOnce"]
          size: 10Gi

      kubelet:
        serviceMonitor:
          https: false