kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
data:
  large-client-header-buffers: "4 16k"
  proxy-buffer-size: "16k"
  proxy-body-size: "10M"
  proxy-read-timeout: "60"
  proxy-send-timeout: "60"
  server-name-hash-bucket-size: "128"
  keep-alive: "75"
  keep-alive-requests: "1024"
  client-header-timeout: "60"
  client-body-timeout: "60"
  upstream-keepalive-timeout: "60"
  max-worker-connections: "2048"
  ssl-protocols: "TLSv1.3 TLSv1.2"
  ssl-ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA"
  ssl-ecdh-curve: "prime256v1:secp384r1"
  ssl-session-tickets: "false"
  ssl-session-cache: "shared:SSL:10m"