apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: nginx-ingress-role
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
rules:
  - apiGroups:
    - ""
    resources: ["configmaps","secrets","endpoints","events","services"]
    verbs: ["list","watch","create","update","delete","get","patch"]
  - apiGroups:
    - ""
    - "extensions"
    resources: ["services","nodes","ingresses","pods","ingresses/status"]
    verbs: ["list","watch","create","update","delete","get","patch"]