config:
subcomponents:
  kv-controller:
    namespace: security
    injectNamespace: true
    config:
      installCrd: false
      keyVault:
        customAuth:
          enabled: false # set to true when use pod identity
          # podIdentitySelector: kv-reader # label used to select azure identity
  env-injector:
    namespace: security
    injectNamespace: true
    config:
      installCrd: true